version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.kryatest.integrations:testflow
  packages:
  - name: EdgeKryatest
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
packages:
- name: EdgeKryatest
  gitServerName: KitTest
  gitUrl: https://github.com/KitNab/EdgeKryatest
  gitUsername: KitNab
  gitToken: edge.scaffolding.EdgeKryatest.KitTest.gitToken
  gitBranch: main
